### ISSUE TITLE
No multi cursor support

### ISSUE THREAD

**Issue by Pustur** [robkorv/slugify-atom#4]
Thanks a lot for the package, unfortunately working with multiple cursors doesn't convert all of them but only one:

```
This is an Example

Another one

i_LOVE_examples

'But no multi cursors?'
```

After `Slugify: Convert`:

```
but-no-multi-cursors

but-no-multi-cursors

but-no-multi-cursors

but-no-multi-cursors
```

Only the last added cursor is considered.

It would be cool to add this feature.
Thanks :)

**Comment by robkorv** [comment]
Tnx for submitting. I'll see if i can find some time this weekend.
